name: terminal
services:
  client:
    cap_drop:
       - ALL
    security_opt:
      - "apparmor:docker-default"
      - "no-new-privileges"
    container_name: terminal.client
    restart: on-failure:5
    depends_on:
      server:
        condition: service_healthy

  server:
    cap_drop:
      - ALL
    security_opt:
      - "apparmor:docker-default"
      - "no-new-privileges"
    container_name: terminal.server
    restart: on-failure:5
    environment:
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Audience=${Jwt__Audience}
      - Jwt__SecretKey=${Jwt__SecretKey}
      - Jwt__AccessTokenExpirationMinutes=${Jwt__AccessTokenExpirationMinutes}
      - Jwt__RefreshTokenExpirationDays=${Jwt__RefreshTokenExpirationDays}
      - Postgres__ConnectionString=${Postgres__ConnectionString}
      - Administrator__Email=${Administrator__Email}
      - Administrator__Password=${Administrator__Password}
    healthcheck:
      test: ["CMD", "curl", "-f", "server:5006/api/ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17-bookworm
    container_name: terminal.postgres
    restart: on-failure:5
    pull_policy: missing
    volumes:
      - terminalData:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  terminalData:
