on:
  workflow_dispatch: # DODANE: Pozwala na ręczne uruchomienie ("Run workflow")
  
  workflow_call:
    inputs:
      registry-url:
        required: true
        type: string
        default: ghcr.io
      registry-username:
        required: true
        type: string
    secrets:
      registry-token:
        required: true
        description: token for authentication to a container registry

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - image-name: client
            context: ./Client
          - image-name: server
            context: ./Server/src
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: login to ${{ inputs.registry-url }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry-url }}
          username: ${{ inputs.registry-username }}
          password: ${{ secrets.registry-token }}

      - name: Set lowercase repository name
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Extract release version
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry-url }}/${{ env.REPO_LC }}/${{ matrix.image-name }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          platforms: linux/amd64,linux/arm64/v8
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push compose stack
        run: |
          # NAPRAWIONE: Używa Twojej nazwy repozytorium zamiast flaviusaugustus
          docker compose -f compose.yaml -f compose.prod.yaml publish -y ${{ inputs.registry-url }}/${{ env.REPO_LC }}/compose:${{ github.sha }}
          docker compose -f compose.yaml -f compose.prod.yaml publish -y ${{ inputs.registry-url }}/${{ env.REPO_LC }}/compose:latest